# Generated by Django 3.2.7 on 2021-09-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='short_url',
            new_name='short_url_em',
        ),
        migrations.AddField(
            model_name='url',
            name='short_url_sym',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
