# Generated by Django 3.2.7 on 2021-09-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20210921_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.TextField(help_text='wdedw'),
        ),
    ]
